{
 "title": "QuickPizza dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total number of recommendations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (pizza_recommendations_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of recommendations with less than 5 ingredients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_ingredients_per_pizza_bucket{le=\"5.0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of recommendations with less than 500 calories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_calories_per_slice_bucket{le=\"500.0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}